FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN corepack enable

COPY package.json ./
COPY pnpm-lock.yaml* ./

RUN pnpm install

COPY . .

ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV WATCHPACK_POLLING=true

EXPOSE 3000

CMD ["pnpm","dev"]